In [1]:
import pandas as pd

In [5]:
train_data = 'train_FD002.txt'
test_data = 'test_FD002.txt'

In [42]:
raw_data = pd.read_csv('E:/Nextstep/MLProjects/YTS/PredictiveMaintenance/Datasets/NASAJetEngine/CMaps/' + train_data, sep = ' ', header = None)

In [43]:
raw_data.dropna(axis=1, inplace=True)

In [50]:
col_names = ['Sensor' + str(i) for i in range(1, len(raw_data.columns)-1)]

In [51]:
col_names.insert(0,['Engine', 'Cycles'])
col_names

[['Engine', 'Cycles'],
 'Sensor1',
 'Sensor2',
 'Sensor3',
 'Sensor4',
 'Sensor5',
 'Sensor6',
 'Sensor7',
 'Sensor8',
 'Sensor9',
 'Sensor10',
 'Sensor11',
 'Sensor12',
 'Sensor13',
 'Sensor14',
 'Sensor15',
 'Sensor16',
 'Sensor17',
 'Sensor18',
 'Sensor19',
 'Sensor20',
 'Sensor21',
 'Sensor22',
 'Sensor23',
 'Sensor24',
 'Sensor25',
 'Sensor26']

In [46]:
raw_data.columns = col_names
raw_data

,Engine,Cycles,Sensor1,Sensor2,Sensor3,Sensor4,Sensor5,Sensor6,Sensor7,Sensor8,...,Sensor15,Sensor16,Sensor17,Sensor18,Sensor19,Sensor20,Sensor21,Sensor22,Sensor23,Sensor24
0,1,1,34.9983,0.8400,100.0,449.44,555.32,1358.61,1137.23,5.48,...,183.06,2387.72,8048.56,9.3461,0.02,334,2223,100.00,14.73,8.8071
1,1,2,41.9982,0.8408,100.0,445.00,549.90,1353.22,1125.78,3.91,...,130.42,2387.66,8072.30,9.3774,0.02,330,2212,100.00,10.41,6.2665
2,1,3,24.9988,0.6218,60.0,462.54,537.31,1256.76,1047.45,7.05,...,164.22,2028.03,7864.87,10.8941,0.02,309,1915,84.93,14.08,8.6723
3,1,4,42.0077,0.8416,100.0,445.00,549.51,1354.03,1126.38,3.91,...,130.72,2387.61,8068.66,9.3528,0.02,329,2212,100.00,10.59,6.4701
4,1,5,25.0005,0.6203,60.0,462.54,537.07,1257.71,1047.93,7.05,...,164.31,2028.00,7861.23,10.8963,0.02,309,1915,84.93,14.13,8.5286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53754,260,312,20.0037,0.7000,100.0,491.19,608.79,1495.60,1269.51,9.35,...,314.05,2389.02,8169.64,9.3035,0.03,369,2324,100.00,24.36,14.5189
53755,260,313,10.0022,0.2510,100.0,489.05,605.81,1514.32,1324.12,10.52,...,371.22,2388.42,8245.36,8.7586,0.03,374,2319,100.00,28.10,16.9454
53756,260,314,25.0041,0.6200,60.0,462.54,537.48,1276.24,1057.92,7.05,...,163.74,2030.33,7971.25,11.0657,0.02,310,1915,84.93,14.19,8.5503
53757,260,315,25.0033,0.6220,60.0,462.54,537.84,1272.95,1066.30,7.05,...,164.37,2030.35,7972.47,11.0537,0.02,311,1915,84.93,14.05,8.3729
53758,260,316,35.0036,0.8400,100.0,449.44,556.64,1374.61,1145.52,5.48,...,183.09,2390.38,8185.35,9.3998,0.02,338,2223,100.00,14.75,8.8446

In [47]:
temp_df = raw_data[['Engine', 'Cycles']].groupby('Engine').max()
#temp_df = raw_data.loc[lst]

In [49]:
raw_data = raw_data.merge(temp_df, how='left', on = 'Engine')
raw_data.rename(columns={'Cycles_y': 'Remaining Cycles'}, inplace=True)
raw_data.drop('Cycles_x', axis=1)

,Engine,Sensor1,Sensor2,Sensor3,Sensor4,Sensor5,Sensor6,Sensor7,Sensor8,Sensor9,...,Sensor17,Sensor18,Sensor19,Sensor20,Sensor21,Sensor22,Sensor23,Sensor24,Remaining Cycles,Cycles
0,1,34.9983,0.8400,100.0,449.44,555.32,1358.61,1137.23,5.48,8.00,...,8048.56,9.3461,0.02,334,2223,100.00,14.73,8.8071,149,149
1,1,41.9982,0.8408,100.0,445.00,549.90,1353.22,1125.78,3.91,5.71,...,8072.30,9.3774,0.02,330,2212,100.00,10.41,6.2665,149,149
2,1,24.9988,0.6218,60.0,462.54,537.31,1256.76,1047.45,7.05,9.02,...,7864.87,10.8941,0.02,309,1915,84.93,14.08,8.6723,149,149
3,1,42.0077,0.8416,100.0,445.00,549.51,1354.03,1126.38,3.91,5.71,...,8068.66,9.3528,0.02,329,2212,100.00,10.59,6.4701,149,149
4,1,25.0005,0.6203,60.0,462.54,537.07,1257.71,1047.93,7.05,9.03,...,7861.23,10.8963,0.02,309,1915,84.93,14.13,8.5286,149,149
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53754,260,20.0037,0.7000,100.0,491.19,608.79,1495.60,1269.51,9.35,13.66,...,8169.64,9.3035,0.03,369,2324,100.00,24.36,14.5189,316,316
53755,260,10.0022,0.2510,100.0,489.05,605.81,1514.32,1324.12,10.52,15.50,...,8245.36,8.7586,0.03,374,2319,100.00,28.10,16.9454,316,316
53756,260,25.0041,0.6200,60.0,462.54,537.48,1276.24,1057.92,7.05,9.04,...,7971.25,11.0657,0.02,310,1915,84.93,14.19,8.5503,316,316
53757,260,25.0033,0.6220,60.0,462.54,537.84,1272.95,1066.30,7.05,9.04,...,7972.47,11.0537,0.02,311,1915,84.93,14.05,8.3729,316,316
53758,260,35.0036,0.8400,100.0,449.44,556.64,1374.61,1145.52,5.48,8.01,...,8185.35,9.3998,0.02,338,2223,100.00,14.75,8.8446,316,316

In [32]:
raw_data

,Engine,Cycles_x,Sensor1,Sensor2,Sensor3,Sensor4,Sensor5,Sensor6,Sensor7,Sensor8,...,Sensor16,Sensor17,Sensor18,Sensor19,Sensor20,Sensor21,Sensor22,Sensor23,Sensor24,Cycles_y
0,1,1,34.9983,0.8400,100.0,449.44,555.32,1358.61,1137.23,5.48,...,2387.72,8048.56,9.3461,0.02,334,2223,100.00,14.73,8.8071,149
1,1,2,41.9982,0.8408,100.0,445.00,549.90,1353.22,1125.78,3.91,...,2387.66,8072.30,9.3774,0.02,330,2212,100.00,10.41,6.2665,149
2,1,3,24.9988,0.6218,60.0,462.54,537.31,1256.76,1047.45,7.05,...,2028.03,7864.87,10.8941,0.02,309,1915,84.93,14.08,8.6723,149
3,1,4,42.0077,0.8416,100.0,445.00,549.51,1354.03,1126.38,3.91,...,2387.61,8068.66,9.3528,0.02,329,2212,100.00,10.59,6.4701,149
4,1,5,25.0005,0.6203,60.0,462.54,537.07,1257.71,1047.93,7.05,...,2028.00,7861.23,10.8963,0.02,309,1915,84.93,14.13,8.5286,149
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53754,260,312,20.0037,0.7000,100.0,491.19,608.79,1495.60,1269.51,9.35,...,2389.02,8169.64,9.3035,0.03,369,2324,100.00,24.36,14.5189,316
53755,260,313,10.0022,0.2510,100.0,489.05,605.81,1514.32,1324.12,10.52,...,2388.42,8245.36,8.7586,0.03,374,2319,100.00,28.10,16.9454,316
53756,260,314,25.0041,0.6200,60.0,462.54,537.48,1276.24,1057.92,7.05,...,2030.33,7971.25,11.0657,0.02,310,1915,84.93,14.19,8.5503,316
53757,260,315,25.0033,0.6220,60.0,462.54,537.84,1272.95,1066.30,7.05,...,2030.35,7972.47,11.0537,0.02,311,1915,84.93,14.05,8.3729,316
53758,260,316,35.0036,0.8400,100.0,449.44,556.64,1374.61,1145.52,5.48,...,2390.38,8185.35,9.3998,0.02,338,2223,100.00,14.75,8.8446,316